/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import negocio.ControladorVisual;

/**
 *
 * @author katia
 */
public class MenuMST extends javax.swing.JFrame {

    /**
     * Creates new form MenuMST2
     */
    public MenuMST() {
        initComponents();
        setSize(1080, 720);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnKruskal = new javax.swing.JButton();
        btnPrim = new javax.swing.JButton();
        btnBoruvka = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Times New Roman", 0, 60)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Árbol de Expansión Mínima");
        lblTitulo.setBorder(javax.swing.BorderFactory.createEmptyBorder(40, 1, 1, 1));
        getContentPane().add(lblTitulo, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(60, 100, 100, 100));
        jPanel1.setLayout(new java.awt.GridLayout(2, 2, 40, 30));

        btnKruskal.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        btnKruskal.setText("1. Kruskal");
        btnKruskal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKruskalActionPerformed(evt);
            }
        });
        jPanel1.add(btnKruskal);

        btnPrim.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        btnPrim.setText("2. Prim");
        btnPrim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimActionPerformed(evt);
            }
        });
        jPanel1.add(btnPrim);

        btnBoruvka.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        btnBoruvka.setText("3. Borůvka");
        btnBoruvka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBoruvkaActionPerformed(evt);
            }
        });
        jPanel1.add(btnBoruvka);

        btnVolver.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        btnVolver.setText("4. Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKruskalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKruskalActionPerformed
        ControladorVisual.getInstancia().abrirPantallaKruskal();
        this.setVisible(false);
    }//GEN-LAST:event_btnKruskalActionPerformed

    private void btnPrimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimActionPerformed
        ControladorVisual.getInstancia().abrirPantallaPrim();
        this.setVisible(false);
    }//GEN-LAST:event_btnPrimActionPerformed

    private void btnBoruvkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBoruvkaActionPerformed
        ControladorVisual.getInstancia().abrirPantallaBoruvka();
        this.setVisible(false);
    }//GEN-LAST:event_btnBoruvkaActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        ControladorVisual.getInstancia().menuPrincipalVisible();
        this.setVisible(false);
    }//GEN-LAST:event_btnVolverActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBoruvka;
    private javax.swing.JButton btnKruskal;
    private javax.swing.JButton btnPrim;
    private javax.swing.JButton btnVolver;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
