/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import base.Grafo;
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import negocio.ControladorGrafo;
import negocio.ControladorVisual;
import org.graphstream.graph.Graph;
import org.graphstream.ui.view.View;
import org.graphstream.ui.view.Viewer;
import resultados.ResultadoKruskal;
import visualizacion.VisualizadorGrafo;
import visualizacion.VisualizadorUtils;

/**
 *
 * @author katia
 */
public class PantallaKruskal extends javax.swing.JFrame {
    
    private final Grafo grafoLogico = ControladorGrafo.getGrafo();
    

    /**
     * Creates new form Kruskal
     */
    public PantallaKruskal() {
        initComponents();
        setLocationRelativeTo(null);
        
        jPanel1.setLayout(new BorderLayout());
        jPanel1.setPreferredSize(new Dimension(500, 300));
        jPanel1.setMinimumSize(new Dimension(500, 300));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnVolver = new javax.swing.JButton();
        btnEjecutar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(700, 500));
        setResizable(false);

        lblTitulo.setFont(new java.awt.Font("Ebrima", 1, 36)); // NOI18N
        lblTitulo.setText("Kruskal");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 569, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 311, Short.MAX_VALUE)
        );

        btnVolver.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 18)); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnEjecutar.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 18)); // NOI18N
        btnEjecutar.setText("Ejecutar");
        btnEjecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEjecutarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addComponent(lblTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(64, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEjecutar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVolver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(304, 304, 304))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEjecutar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(btnVolver)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        ControladorVisual.getInstancia().abrirPantallaMenuMST();
        this.setVisible(false);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnEjecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEjecutarActionPerformed
        
        btnEjecutar.setEnabled(false);

        new Thread(() -> {
            try {
                Thread.sleep(500);
                
                if (grafoLogico.getLocalidades().isEmpty() || grafoLogico.getCarreteras().isEmpty()) {
                    SwingUtilities.invokeLater(() ->
                            JOptionPane.showMessageDialog(this, "El grafo lógico está vacío. No se puede ejecutar Kruskal.")
                    );
                    return;
                }

                SwingUtilities.invokeLater(() -> {
                    // Limpia el panel
                    jPanel1.removeAll();
                    jPanel1.revalidate();
                    jPanel1.repaint();

                    // Crea el grafo visual desde el lógico
                    Graph grafoVisual = VisualizadorGrafo.crearGrafoVisual(grafoLogico);
                    VisualizadorUtils.reiniciarGrafo(grafoVisual);

                    Viewer viewer = new Viewer(grafoVisual, Viewer.ThreadingModel.GRAPH_IN_ANOTHER_THREAD);
                    viewer.enableAutoLayout();
                    View view = viewer.addDefaultView(false);
                    jPanel1.setLayout(new BorderLayout());
                    jPanel1.add((Component) view, BorderLayout.CENTER);
                    jPanel1.revalidate();

                    // Ejecuta Kruskal
                    new Thread(() -> {
                        try {
                            ResultadoKruskal resultado = algoritmos.Kruskal.ejecutar(grafoLogico, grafoVisual);
                            double peso = resultado.getPesoTotal();
                            SwingUtilities.invokeLater(() ->
                                    JOptionPane.showMessageDialog(this, "Peso total del MST: " + peso + " km")
                            );
                        } catch (Exception e) {
                            e.printStackTrace();
                        } finally {
                            SwingUtilities.invokeLater(() -> btnEjecutar.setEnabled(true));
                        }
                    }).start();

                });

            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }).start();
    }//GEN-LAST:event_btnEjecutarActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEjecutar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
