/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import algoritmos.BFS;
import algoritmos.DFS;
import base.Grafo;
import base.Localidad;
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Dimension;
import javax.swing.SwingUtilities;
import negocio.ControladorGrafo;
import negocio.ControladorVisual;
import org.graphstream.graph.Graph;
import org.graphstream.ui.view.View;
import org.graphstream.ui.view.Viewer;
import resultados.ResultadoBFS;
import visualizacion.VisualizadorGrafo;
import visualizacion.VisualizadorUtils;
import org.graphstream.ui.view.Viewer;

/**
 *
 * @author pedro
 */
public class Recorridos extends javax.swing.JFrame {

    private final Grafo grafoLogico = ControladorGrafo.getGrafo();
    private final Graph grafoVisual = VisualizadorGrafo.crearGrafoVisual(grafoLogico);

    public Recorridos() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setSize(700, 500);
        pnlGrafo.setLayout(new BorderLayout());
        pnlGrafo.setPreferredSize(new Dimension(500, 300));
        pnlGrafo.setMinimumSize(new Dimension(500, 300));
        Viewer viewer = new Viewer(grafoVisual, Viewer.ThreadingModel.GRAPH_IN_ANOTHER_THREAD);
        viewer.enableAutoLayout();
        View view = viewer.addDefaultView(false);
        pnlGrafo.setLayout(new BorderLayout());
        pnlGrafo.add((Component) view, BorderLayout.CENTER);
        pnlGrafo.revalidate();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlGrafo = new javax.swing.JPanel();
        btnDFS = new javax.swing.JButton();
        btnBFS = new javax.swing.JButton();
        lblRecorrido = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        lblAlgoritmo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlGrafo.setMinimumSize(new java.awt.Dimension(497, 290));

        javax.swing.GroupLayout pnlGrafoLayout = new javax.swing.GroupLayout(pnlGrafo);
        pnlGrafo.setLayout(pnlGrafoLayout);
        pnlGrafoLayout.setHorizontalGroup(
            pnlGrafoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 497, Short.MAX_VALUE)
        );
        pnlGrafoLayout.setVerticalGroup(
            pnlGrafoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );

        jPanel1.add(pnlGrafo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, 290));

        btnDFS.setText("DFS");
        btnDFS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDFSActionPerformed(evt);
            }
        });
        jPanel1.add(btnDFS, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, 100, 50));

        btnBFS.setText("BFS");
        btnBFS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBFSActionPerformed(evt);
            }
        });
        jPanel1.add(btnBFS, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 100, 50));

        lblRecorrido.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblRecorrido.setText("Recorridos");
        jPanel1.add(lblRecorrido, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, -1, -1));

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 420, -1, -1));
        jPanel1.add(lblAlgoritmo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 180, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        this.dispose();
        ControladorVisual.getInstancia().menuPrincipalVisible();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnBFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBFSActionPerformed
        VisualizadorUtils.reiniciarGrafo(grafoVisual);
        String ciudadInicio = "León";
        lblAlgoritmo.setText("Algoritmo en ejecución: BFS");
        Localidad origen = grafoLogico.getLocalidades().stream()
                .filter(l -> l.getNombre().equals(ciudadInicio))
                .findFirst()
                .orElse(null);

        if (origen != null) {
            btnDFS.setEnabled(false);
            btnBFS.setEnabled(false);
            new Thread(() -> {
                try {
                    Thread.sleep(500);
                    BFS.ejecutar(grafoLogico, origen, grafoVisual);

                } catch (InterruptedException e) {
                    e.printStackTrace();
                } finally {

                    SwingUtilities.invokeLater(() -> btnDFS.setEnabled(true));
                    SwingUtilities.invokeLater(() -> btnBFS.setEnabled(true));

                }
            }).start();
        }
     }//GEN-LAST:event_btnBFSActionPerformed

    private void btnDFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDFSActionPerformed
        VisualizadorUtils.reiniciarGrafo(grafoVisual);
        String ciudadInicio = "León";
        lblAlgoritmo.setText("Algoritmo en ejecución: DFS");

        Localidad origen = grafoLogico.getLocalidades().stream()
                .filter(l -> l.getNombre().equals(ciudadInicio))
                .findFirst()
                .orElse(null);

        if (origen != null) {
            btnDFS.setEnabled(false);
            btnBFS.setEnabled(false);
            new Thread(() -> {
                try {
                    Thread.sleep(500);
                    DFS.ejecutar(grafoLogico, origen, grafoVisual);

                } catch (InterruptedException e) {
                    e.printStackTrace();
                } finally {
                    SwingUtilities.invokeLater(() -> btnDFS.setEnabled(true));
                    SwingUtilities.invokeLater(() -> btnBFS.setEnabled(true));

                }
            }).start();
        }
    }//GEN-LAST:event_btnDFSActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBFS;
    private javax.swing.JButton btnDFS;
    private javax.swing.JButton btnVolver;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAlgoritmo;
    private javax.swing.JLabel lblRecorrido;
    private javax.swing.JPanel pnlGrafo;
    // End of variables declaration//GEN-END:variables
}
