/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import algoritmos.BFS;
import algoritmos.DFS;
import base.Grafo;
import base.Localidad;
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Dimension;
import javax.swing.SwingUtilities;
import negocio.ControladorGrafo;
import negocio.ControladorVisual;
import org.graphstream.graph.Graph;
import org.graphstream.ui.view.View;
import org.graphstream.ui.view.Viewer;
import resultados.ResultadoBFS;
import visualizacion.VisualizadorGrafo;
import visualizacion.VisualizadorUtils;
import org.graphstream.ui.view.Viewer;

/**
 *
 * @author Pedro, Christopher y Katia
 */
public class Recorridos extends javax.swing.JFrame {

    private final Grafo grafoLogico = ControladorGrafo.getGrafo();
    private final Graph grafoVisual = VisualizadorGrafo.crearGrafoVisual(grafoLogico);

    public Recorridos() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setSize(1080, 720);
        pnlGrafo.setLayout(new BorderLayout());
        pnlGrafo.setPreferredSize(new Dimension(1280, 720));
        pnlGrafo.setMinimumSize(new Dimension(1280, 720));
        Viewer viewer = new Viewer(grafoVisual, Viewer.ThreadingModel.GRAPH_IN_ANOTHER_THREAD);
        viewer.enableAutoLayout();
        View view = viewer.addDefaultView(false);

        pnlGrafo.setLayout(new BorderLayout());
        pnlGrafo.add((Component) view, BorderLayout.CENTER);
        pnlGrafo.revalidate();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        pnlGrafo = new javax.swing.JPanel();
        btnDFS = new javax.swing.JButton();
        btnBFS = new javax.swing.JButton();
        lblRecorrido = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        lblAlgoritmo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlPrincipal.setPreferredSize(new java.awt.Dimension(1080, 720));
        pnlPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlGrafo.setMinimumSize(new java.awt.Dimension(497, 290));

        javax.swing.GroupLayout pnlGrafoLayout = new javax.swing.GroupLayout(pnlGrafo);
        pnlGrafo.setLayout(pnlGrafoLayout);
        pnlGrafoLayout.setHorizontalGroup(
            pnlGrafoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 890, Short.MAX_VALUE)
        );
        pnlGrafoLayout.setVerticalGroup(
            pnlGrafoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        pnlPrincipal.add(pnlGrafo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 890, 480));

        btnDFS.setText("DFS");
        btnDFS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDFSActionPerformed(evt);
            }
        });
        pnlPrincipal.add(btnDFS, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 560, 100, 50));

        btnBFS.setText("BFS");
        btnBFS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBFSActionPerformed(evt);
            }
        });
        pnlPrincipal.add(btnBFS, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 560, 100, 50));

        lblRecorrido.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblRecorrido.setText("Recorridos");
        pnlPrincipal.add(lblRecorrido, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, -1, -1));

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        pnlPrincipal.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 630, -1, -1));
        pnlPrincipal.add(lblAlgoritmo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 180, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        this.dispose();
        ControladorVisual.getInstancia().menuPrincipalVisible();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnBFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBFSActionPerformed
        VisualizadorUtils.reiniciarGrafo(grafoVisual);
        String ciudadInicio = "León";
        lblAlgoritmo.setText("Algoritmo en ejecución: BFS");
        Localidad origen = grafoLogico.getLocalidades().stream()
                .filter(l -> l.getNombre().equals(ciudadInicio))
                .findFirst()
                .orElse(null);

        if (origen != null) {
            btnDFS.setEnabled(false);
            btnBFS.setEnabled(false);
            new Thread(() -> {
                try {
                    Thread.sleep(500);
                    BFS.ejecutar(grafoLogico, origen, grafoVisual);

                } catch (InterruptedException e) {
                    e.printStackTrace();
                } finally {

                    SwingUtilities.invokeLater(() -> btnDFS.setEnabled(true));
                    SwingUtilities.invokeLater(() -> btnBFS.setEnabled(true));

                }
            }).start();
        }
     }//GEN-LAST:event_btnBFSActionPerformed

    private void btnDFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDFSActionPerformed
        VisualizadorUtils.reiniciarGrafo(grafoVisual);
        String ciudadInicio = "León";
        lblAlgoritmo.setText("Algoritmo en ejecución: DFS");

        Localidad origen = grafoLogico.getLocalidades().stream()
                .filter(l -> l.getNombre().equals(ciudadInicio))
                .findFirst()
                .orElse(null);

        if (origen != null) {
            btnDFS.setEnabled(false);
            btnBFS.setEnabled(false);
            new Thread(() -> {
                try {
                    Thread.sleep(500);
                    DFS.ejecutar(grafoLogico, origen, grafoVisual);

                } catch (InterruptedException e) {
                    e.printStackTrace();
                } finally {
                    SwingUtilities.invokeLater(() -> btnDFS.setEnabled(true));
                    SwingUtilities.invokeLater(() -> btnBFS.setEnabled(true));

                }
            }).start();
        }
    }//GEN-LAST:event_btnDFSActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBFS;
    private javax.swing.JButton btnDFS;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel lblAlgoritmo;
    private javax.swing.JLabel lblRecorrido;
    private javax.swing.JPanel pnlGrafo;
    private javax.swing.JPanel pnlPrincipal;
    // End of variables declaration//GEN-END:variables
}
